ALTER TABLE Users ADD COLUMN totalBytesUsed INTEGER DEFAULT 0;
ALTER TABLE Users ADD COLUMN lastConnectTime DATETIME;
ALTER TABLE Users ADD COLUMN lastConnectIp TEXT;
ALTER TABLE Users ADD COLUMN lastClientSoftware TEXT;
